project_id = "zbgcvuocupxfugtfjids"

[functions.ai-study-advisor]
verify_jwt = false

[functions.ai-course-recommendations]
verify_jwt = false

[functions.ai-email-draft]
verify_jwt = false

[functions.moderate-image]
verify_jwt = false
